"""
netCDF -> the files the web viewer loads.

Every file is JavaScript that assigns a global (`window.VOXEL_*`), loaded by a
<script> tag, so the viewer works from a static server AND straight from
file://, where browsers refuse fetch() of a local file.

Concentration is sent as one uint8 per voxel on a log scale:

    0          building / no data
    1          below the scale (C < C_max / 10^decades, including C = 0)
    2 .. 255   log10(C) uniformly over [log10(C_max) - decades, log10(C_max)]

With 4 decades the step is 10^(4/253) = +3.7 %, so a decoded value is within
1.8 % of the true one - far inside any model uncertainty - and a scenario is
500 kB before base64 instead of 2 MB of float32.
"""

from __future__ import annotations

import base64
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import geopandas as gpd
import numpy as np
from pyproj import Transformer

from project_config import REPO_ROOT, get_required, resolve_repo_path

from analysis import operators as ops
from analysis.fields import ConcentrationField
from analysis.pipeline import load_scenario, thresholds

CODE_NO_DATA = 0
CODE_BELOW = 1
CODE_FIRST = 2
CODE_LAST = 255
LEVELS = CODE_LAST - CODE_FIRST  # 253 steps between first and last code


def quantise_log(values: np.ndarray, c_max: float, decades: float) -> np.ndarray:
    """Encode C as uint8 codes; see the module docstring for the code table."""

    if decades <= 0.0:
        raise ValueError("decades must be positive")

    values = np.asarray(values, dtype=float)
    codes = np.full(values.shape, CODE_BELOW, dtype=np.uint8)
    codes[np.isnan(values)] = CODE_NO_DATA

    if not np.isfinite(c_max) or c_max <= 0.0:
        return codes  # EC-3: an all-zero field has no log scale to build

    log_min = np.log10(c_max) - decades
    in_range = ~np.isnan(values) & (values >= 10.0**log_min)

    position = (np.log10(values[in_range]) - log_min) / decades * LEVELS
    codes[in_range] = np.clip(np.rint(position) + CODE_FIRST, CODE_FIRST, CODE_LAST).astype(np.uint8)

    return codes


def dequantise_log(codes: np.ndarray, c_max: float, decades: float) -> np.ndarray:
    """Inverse of `quantise_log`: NaN for no data, 0 for below the scale."""

    codes = np.asarray(codes, dtype=np.uint8)
    values = np.zeros(codes.shape, dtype=float)
    values[codes == CODE_NO_DATA] = np.nan

    if np.isfinite(c_max) and c_max > 0.0:
        log_min = np.log10(c_max) - decades
        coded = codes >= CODE_FIRST
        values[coded] = 10.0 ** (log_min + (codes[coded].astype(float) - CODE_FIRST) / LEVELS * decades)

    return values


def domain_corners_wgs84(field_: ConcentrationField) -> dict[str, list[float]]:
    """Outer corners of the grid (cell EDGES, not centres) as [lon, lat]."""

    _, dy, dx = field_.spacing
    west, east = field_.x[0] - dx / 2, field_.x[-1] + dx / 2
    south, north = field_.y[0] - dy / 2, field_.y[-1] + dy / 2

    to_wgs84 = Transformer.from_crs(field_.crs, "EPSG:4326", always_xy=True)
    corners = {"sw": (west, south), "se": (east, south), "ne": (east, north), "nw": (west, north)}

    return {name: [float(v) for v in to_wgs84.transform(x, y)] for name, (x, y) in corners.items()}


def bilinear_nodes(corners: dict[str, list[float]], nx: int, ny: int) -> np.ndarray:
    """
    Grid-node [lon, lat] for (ny+1, nx+1) nodes, bilinear in the four corners.

    This is what the viewer does in JavaScript; tests check it against an
    exact pyproj projection of every node.
    """

    s = np.linspace(0.0, 1.0, nx + 1)[None, :, None]
    t = np.linspace(0.0, 1.0, ny + 1)[:, None, None]
    sw, se, ne, nw = (np.asarray(corners[k])[None, None, :] for k in ("sw", "se", "ne", "nw"))

    return (1 - s) * (1 - t) * sw + s * (1 - t) * se + s * t * ne + (1 - s) * t * nw


def _js_global(name: str, payload: Any) -> str:
    body = json.dumps(payload, ensure_ascii=False, separators=(",", ":"))
    return f"// Generated by src/06_export_web.py - do not edit.\nwindow.{name} = {body};\n"


def _js_scenario(scenario: str, payload: Any) -> str:
    body = json.dumps(payload, ensure_ascii=False, separators=(",", ":"))
    return (
        "// Generated by src/06_export_web.py - do not edit.\n"
        "window.VOXEL_DATA = window.VOXEL_DATA || {};\n"
        f"window.VOXEL_DATA[{json.dumps(scenario)}] = {body};\n"
    )


def _round_geometry(frame: gpd.GeoDataFrame, digits: int = 7) -> dict[str, Any]:
    """GeoJSON with coordinates rounded to ~1 cm, to keep the file small."""

    data = json.loads(frame.to_json(drop_id=True))

    def round_coords(value: Any) -> Any:
        if isinstance(value, (list, tuple)):
            return [round_coords(item) for item in value]
        if isinstance(value, float):
            return round(value, digits)
        return value

    for feature in data["features"]:
        feature["geometry"]["coordinates"] = round_coords(feature["geometry"]["coordinates"])

    return data


def export_buildings(config: dict[str, Any]) -> dict[str, Any]:
    buildings = gpd.read_file(resolve_repo_path(config, "paths.processed_buildings")).to_crs("EPSG:4326")
    keep = buildings[["resolved_height_m", "height_source", "geometry"]].rename(columns={"resolved_height_m": "height_m"})
    keep["height_m"] = keep["height_m"].astype(float).round(1)
    return _round_geometry(keep)


def export_roads(config: dict[str, Any]) -> dict[str, Any] | None:
    path = resolve_repo_path(config, "paths.road_emissions")

    if not path.exists():
        return None

    roads = gpd.read_file(path).to_crs("EPSG:4326")
    keep = roads[["highway", "name", "emission_share", "geometry"]].copy()
    keep["emission_share"] = keep["emission_share"].astype(float).round(5)
    return _round_geometry(keep)


def scenario_payload(field_: ConcentrationField, config: dict[str, Any]) -> tuple[dict[str, Any], dict[str, Any]]:
    """(manifest entry, data payload) for one scenario."""

    decades = float(get_required(config, "web.log_decades"))
    c = field_.concentration
    c_max = float(np.nanmax(c)) if np.any(~np.isnan(c)) else 0.0
    dz, dy, dx = field_.spacing
    limits = thresholds(config)

    codes = quantise_log(c, c_max, decades)

    entry = {
        "id": field_.scenario,
        "model": str(field_.attrs.get("model")),
        "model_description": str(field_.attrs.get("model_description", "")),
        "wind_from_deg": float(field_.attrs["wind_from_deg"]),
        "wind_speed_m_s": float(field_.attrs["wind_speed_m_s"]),
        "file": f"scenario_{field_.scenario}.js",
        "scale": {"c_max": c_max, "decades": decades, "levels": LEVELS, "first_code": CODE_FIRST},
    }

    payload = {
        "codes_base64": base64.b64encode(codes.tobytes(order="C")).decode("ascii"),
        # exact, from float data - the viewer shows these for multiplier 1, background 0
        "layer_mean_ug_m3": [None if np.isnan(v) else float(v) for v in ops.layer_means(c, field_.solid)],
        "exceedance_volume_by_layer_m3": {
            key: ops.exceedance_volume_by_layer(c, field_.solid, item["value"], dx, dy, dz).tolist()
            for key, item in limits.items()
        },
    }

    return entry, payload


def export_web(config: dict[str, Any]) -> dict[str, Any]:
    """Write every web/data file and return a summary including the byte count."""

    out_dir = (REPO_ROOT / get_required(config, "web.output_dir")).resolve()
    out_dir.mkdir(parents=True, exist_ok=True)
    budget = int(get_required(config, "web.size_budget_bytes"))

    fields = [load_scenario(config, scenario) for scenario in get_required(config, "web.scenarios")]

    if not fields:
        raise ValueError("web.scenarios is empty")

    reference = fields[0]
    for other in fields[1:]:
        if other.concentration.shape != reference.concentration.shape or other.crs != reference.crs:
            raise ValueError(f"scenario {other.scenario} is on a different grid")

    dz, dy, dx = reference.spacing
    corners = domain_corners_wgs84(reference)

    files: dict[str, str] = {}
    entries = []

    for field_ in fields:
        entry, payload = scenario_payload(field_, config)
        entries.append(entry)
        files[entry["file"]] = _js_scenario(field_.scenario, payload)

    manifest = {
        "generated_utc": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%MZ"),
        "units": "µg/m³",
        "pollutant": "PM2.5 (phần đóng góp của giao thông trong miền, chuẩn hoá EDGAR)",
        "grid": {
            "nx": int(reference.x.size), "ny": int(reference.y.size), "nz": int(reference.z.size),
            "dx_m": dx, "dy_m": dy, "dz_m": dz,
            "z_centres_m": reference.z.tolist(),
            "order": "z,y,x; y increases northward, x eastward",
            "model_crs": reference.crs,
        },
        "corners_wgs84": corners,
        "thresholds": thresholds(config),
        "scenarios": entries,
        # buildings are code 0 in every scenario, so no separate mask is shipped
        "quantisation": "uint8 log: 0 = nhà/không dữ liệu, 1 = dưới thang, 2..255 = log10(C) đều trên [C_max/10^decades, C_max]",
        "provenance": {
            "buildings": "OSM footprints + Google Open Buildings 2.5D heights (MAE tự đo 23,2 m; trần 100 m)",
            "roads": "OSM drive network, mỗi phố hai chiều tính một lần",
            "emissions": "EDGAR v8.1 TRO 2022, phân bổ theo cấp đường (docs/emission_assumptions.md)",
            "meteorology": "Open-Meteo, hai kịch bản mùa (config meteorology.scenarios)",
            "basemap": "OpenFreeMap © OpenMapTiles Data from OpenStreetMap",
        },
    }

    files["manifest.js"] = _js_global("VOXEL_MANIFEST", manifest)
    files["buildings.js"] = _js_global("VOXEL_BUILDINGS", export_buildings(config))

    roads = export_roads(config)
    if roads is not None:
        files["roads.js"] = _js_global("VOXEL_ROADS", roads)

    sizes = {}
    for name, text in files.items():
        path = out_dir / name
        path.write_text(text, encoding="utf-8")
        sizes[name] = path.stat().st_size

    # Scenario files from an earlier export that is no longer configured.
    for stale in out_dir.glob("scenario_*.js"):
        if stale.name not in files:
            stale.unlink()

    total = int(sum(sizes.values()))

    if total >= budget:
        raise ValueError(f"web/data is {total:,} bytes, over the {budget:,}-byte budget")

    return {"output_dir": str(out_dir), "bytes": sizes, "total_bytes": total, "budget_bytes": budget}
